ohio_counties = {
    "Adams County": ["West Union", "Peebles", "Seaman"],
    "Allen County": ["Lima", "Beaverdam", "Delphos"],
    "Ashland County": ["Ashland", "Loudonville", "Ontario"],
    "Ashtabula County": ["Ashtabula", "Conneaut", "Geneva", "Jefferson", "Painesville"],
    "Athens County": ["Athens", "Coolville", "Albany", "Nelsonville"],
    "Auglaize County": ["Wapakoneta", "St. Marys", "Minster", "New Knoxville"],
    "Belmont County": ["St. Clairsville", "Martins Ferry", "Bridgeport", "Powhatan Point"],
    "Brown County": ["Georgetown", "Mount Orab", "Aberdeen"],
    "Butler County": ["Hamilton", "Fairfield", "Middletown", "Trenton", "Oxford", "Monroe"],
    "Carroll County": ["Carrollton", "Malvern", "Dellroy"],
    "Champaign County": ["Urbana", "West Liberty", "Mechanicsburg"],
    "Clark County": ["Springfield", "Enon", "South Charleston"],
    "Clermont County": ["Batavia", "Amelia", "Milford", "Loveland"],
    "Clinton County": ["Wilmington", "Blanchester", "Sabina"],
    "Columbiana County": ["Lisbon", "Salem", "East Liverpool", "Columbiana"],
    "Coshocton County": ["Coshocton", "Conesville", "West Lafayette"],
    "Crawford County": ["Bucyrus", "Galion", "Crestline"],
    "Cuyahoga County": ["Cleveland", "Parma", "Lakewood", "Euclid", "Cleveland Heights", "Strongsville"],
    "Darke County": ["Greenville", "Union City", "Ansonia"],
    "Defiance County": ["Defiance", "Hicksville", "Sherwood"],
    "Delaware County": ["Delaware", "Powell", "Olentangy", "Sunbury"],
    "Erie County": ["Sandusky", "Huron", "Vermilion", "Port Clinton"],
    "Fairfield County": ["Lancaster", "Pickerington", "Baltimore", "Berne"],
    "Fayette County": ["Washington Court House", "Junction City", "Jeffersonville"],
    "Franklin County": ["Columbus", "Bexley", "Gahanna", "Upper Arlington", "Whitehall", "Westerville", "Dublin", "New Albany"],
    "Fulton County": ["Wauseon", "Swanton", "Delta"],
    "Gallia County": ["Gallipolis", "Bidwell", "Vinton"],
    "Geauga County": ["Chardon", "Middlefield", "Parkman", "Burton"],
    "Greene County": ["Xenia", "Fairborn", "Bellbrook", "Beavercreek"],
    "Guernsey County": ["Cambridge", "Byesville", "Quincy"],
    "Hamilton County": ["Cincinnati", "Norwood", "Blue Ash", "Loveland", "Cheviot", "Forest Park"],
    "Hancock County": ["Findlay", "Mount Blanchard", "Arcadia"],
    "Hardin County": ["Kenton", "Ada", "McGuffey"],
    "Harrison County": ["Cadiz", "Harrison", "New Athens"],
    "Henry County": ["Napoleon", "Holgate", "Hicksville"],
    "Highland County": ["Hillsboro", "Greenfield", "Leesburg"],
    "Hocking County": ["Logan", "Buchtel", "Rockbridge"],
    "Holmes County": ["Millersburg", "Berlin", "Walnut Creek"],
    "Huron County": ["Norwalk", "Willard", "Monroeville"],
    "Jackson County": ["Jackson", "Oak Hill", "Wellston"],
    "Jefferson County": ["Steubenville", "Toronto", "Tiltonsville"],
    "Knox County": ["Mount Vernon", "Fredericktown", "Danville"],
    "Lake County": ["Painesville", "Mentor", "Willoughby", "Concord"],
    "Lawrence County": ["Ironton", "Coal Grove", "Hanging Rock"],
    "Licking County": ["Newark", "Pataskala", "Heath", "Johnstown"],
    "Logan County": ["Bellefontaine", "Rushsylvania", "Zanesfield"],
    "Lorain County": ["Lorain", "Elyria", "Amherst", "North Ridgeville"],
    "Lucas County": ["Toledo", "Sylvania", "Maumee", "Oregon", "Waterville"],
    "Madison County": ["London", "Mount Sterling", "Grove City"],
    "Mahoning County": ["Youngstown", "Struthers", "Boardman"],
    "Marion County": ["Marion", "La Rue", "Caledonia"],
    "Medina County": ["Medina", "Wadsworth", "Brunswick"],
    "Meigs County": ["Pomeroy", "Middleport", "Racine"],
    "Mercer County": ["Celina", "St. Henry", "Coldwater"],
    "Miami County": ["Troy", "Piqua", "Tippecanoe", "Casstown"],
    "Monroe County": ["Woodsfield", "Beallsville", "Powellsville"],
    "Montgomery County": ["Dayton", "Kettering", "Centerville", "Moraine"],
    "Morgan County": ["McConnelsville", "Stockport", "Chesterhill"],
    "Morrow County": ["Mount Gilead", "Marengo", "Cardington"],
    "Muskingum County": ["Zanesville", "New Concord", "Frazeysburg"],
    "Noble County": ["Caldwell", "Shawnee", "Sarahsville"],
    "Ottawa County": ["Port Clinton", "Oak Harbor", "Put-in-Bay"],
    "Paulding County": ["Paulding", "Oakwood", "Antwerp"],
    "Perry County": ["New Lexington", "Somerset", "Sherrodsville"],
    "Pickaway County": ["Circleville", "Ashville", "Logan Elm Village"],
    "Pike County": ["Waverly", "Piketon", "Oak Hill"],
    "Portage County": ["Ravenna", "Kent", "Brimfield"],
    "Preble County": ["Eaton", "Camden", "Lewisburg"],
    "Putnam County": ["Ottawa", "Leipsic", "Kalida"],
    "Richland County": ["Mansfield", "Ontario", "Shelby"],
    "Ross County": ["Chillicothe", "Frankfort", "Huntington"],
    "Sandusky County": ["Fremont", "Clyde", "Green Springs"],
    "Scioto County": ["Portsmouth", "Lucasville", "Wheelersburg"],
    "Seneca County": ["Tiffin", "Fostoria", "Attica"],
    "Shelby County": ["Sidney", "Anna", "Russia"],
    "Stark County": ["Canton", "Massillon", "North Canton"],
    "Summit County": ["Akron", "Cuyahoga Falls", "Stow", "Barberton"],
    "Trumbull County": ["Warren", "Niles", "Girard", "Howland"],
    "Tuscarawas County": ["New Philadelphia", "Dover", "Dennison"],
    "Union County": ["Marysville", "Plain City", "Unionville Center"],
    "Van Wert County": ["Van Wert", "Delphos", "Creston"],
    "Vinton County": ["McArthur", "Hamden", "Zaleski"],
    "Warren County": ["Lebanon", "Mason", "Springboro"],
    "Washington County": ["Marietta", "Belpre", "Macksburg"],
    "Wayne County": ["Wooster", "Rittman", "Creston"],
    "Williams County": ["Bryan", "Montpelier", "Edgerton"],
    "Wood County": ["Bowling Green", "Oregon", "Perrysburg"],
    "Wyandot County": ["Upper Sandusky", "Sycamore", "Wharton"]
}

ohio_cities = {
    "Columbus": 907971.0,
    "Cleveland": 361607.0,
    "Cincinnati": 309513.0,
    "Toledo": 266301.0,
    "Akron": 188509.0,
    "Dayton": 135944.0,
    "Parma": 79358.0,
    "Canton": 69671.0,
    "Lorain": 65365.0,
    "Hamilton": 62937.0,
    "Youngstown": 59144.0,
    "Springfield": 58106.0,
    "Dublin": 48893.0,
    "Westerville": 38911.0,
    "Upper Arlington": 36010.0,
    "Delaware": 41900.0,
    "Hilliard": 36103.0,
    "Worthington": 14680.0,
    "Bexley": 12936.0,
    "Grove City": 42385.0,
    "Gahanna": 35127.0,
    "Reynoldsburg": 29643.0,
    "Pickerington": 23828.0,
    "New Albany": 11021.0,
    "Canal Winchester": 7945.0,
    "Marysville": 27157.0
}
