ohio_counties = {
    "Adams County": ["West Union", "Peebles", "Seaman"],
    "Allen County": ["Lima", "Beaverdam", "Delphos"],
    "Ashland County": ["Ashland", "Loudonville", "Ontario"],
    "Ashtabula County": ["Ashtabula", "Conneaut", "Geneva", "Jefferson", "Painesville"],
    "Athens County": ["Athens", "Coolville", "Albany", "Nelsonville"],
    "Auglaize County": ["Wapakoneta", "St. Marys", "Minster", "New Knoxville"],
    "Belmont County": ["St. Clairsville", "Martins Ferry", "Bridgeport", "Powhatan Point"],
    "Brown County": ["Georgetown", "Mount Orab", "Aberdeen"],
    "Butler County": ["Hamilton", "Fairfield", "Middletown", "Trenton", "Oxford", "Monroe"],
    "Carroll County": ["Carrollton", "Malvern", "Dellroy"],
    "Champaign County": ["Urbana", "West Liberty", "Mechanicsburg"],
    "Clark County": ["Springfield", "Enon", "South Charleston"],
    "Clermont County": ["Batavia", "Amelia", "Milford", "Loveland"],
    "Clinton County": ["Wilmington", "Blanchester", "Sabina"],
    "Columbiana County": ["Lisbon", "Salem", "East Liverpool", "Columbiana"],
    "Coshocton County": ["Coshocton", "Conesville", "West Lafayette"],
    "Crawford County": ["Bucyrus", "Galion", "Crestline"],
    "Cuyahoga County": ["Cleveland", "Parma", "Lakewood", "Euclid", "Cleveland Heights", "Strongsville"],
    "Darke County": ["Greenville", "Union City", "Ansonia"],
    "Defiance County": ["Defiance", "Hicksville", "Sherwood"],
    "Delaware County": ["Delaware", "Powell", "Olentangy", "Sunbury"],
    "Erie County": ["Sandusky", "Huron", "Vermilion", "Port Clinton"],
    "Fairfield County": ["Lancaster", "Pickerington", "Baltimore", "Berne"],
    "Fayette County": ["Washington Court House", "Junction City", "Jeffersonville"],
    "Franklin County": ["Columbus", "Bexley", "Gahanna", "Upper Arlington", "Whitehall", "Westerville", "Dublin", "New Albany"],
    "Fulton County": ["Wauseon", "Swanton", "Delta"],
    "Gallia County": ["Gallipolis", "Bidwell", "Vinton"],
    "Geauga County": ["Chardon", "Middlefield", "Parkman", "Burton"],
    "Greene County": ["Xenia", "Fairborn", "Bellbrook", "Beavercreek"],
    "Guernsey County": ["Cambridge", "Byesville", "Quincy"],
    "Hamilton County": ["Cincinnati", "Norwood", "Blue Ash", "Loveland", "Cheviot", "Forest Park"],
    "Hancock County": ["Findlay", "Mount Blanchard", "Arcadia"],
    "Hardin County": ["Kenton", "Ada", "McGuffey"],
    "Harrison County": ["Cadiz", "Harrison", "New Athens"],
    "Henry County": ["Napoleon", "Holgate", "Hicksville"],
    "Highland County": ["Hillsboro", "Greenfield", "Leesburg"],
    "Hocking County": ["Logan", "Buchtel", "Rockbridge"],
    "Holmes County": ["Millersburg", "Berlin", "Walnut Creek"],
    "Huron County": ["Norwalk", "Willard", "Monroeville"],
    "Jackson County": ["Jackson", "Oak Hill", "Wellston"],
    "Jefferson County": ["Steubenville", "Toronto", "Tiltonsville"],
    "Knox County": ["Mount Vernon", "Fredericktown", "Danville"],
    "Lake County": ["Painesville", "Mentor", "Willoughby", "Concord"],
    "Lawrence County": ["Ironton", "Coal Grove", "Hanging Rock"],
    "Licking County": ["Newark", "Pataskala", "Heath", "Johnstown"],
    "Logan County": ["Bellefontaine", "Rushsylvania", "Zanesfield"],
    "Lorain County": ["Lorain", "Elyria", "Amherst", "North Ridgeville"],
    "Lucas County": ["Toledo", "Sylvania", "Maumee", "Oregon", "Waterville"],
    "Madison County": ["London", "Mount Sterling", "Grove City"],
    "Mahoning County": ["Youngstown", "Struthers", "Boardman"],
    "Marion County": ["Marion", "La Rue", "Caledonia"],
    "Medina County": ["Medina", "Wadsworth", "Brunswick"],
    "Meigs County": ["Pomeroy", "Middleport", "Racine"],
    "Mercer County": ["Celina", "St. Henry", "Coldwater"],
    "Miami County": ["Troy", "Piqua", "Tippecanoe", "Casstown"],
    "Monroe County": ["Woodsfield", "Beallsville", "Powellsville"],
    "Montgomery County": ["Dayton", "Kettering", "Centerville", "Moraine"],
    "Morgan County": ["McConnelsville", "Stockport", "Chesterhill"],
    "Morrow County": ["Mount Gilead", "Marengo", "Cardington"],
    "Muskingum County": ["Zanesville", "New Concord", "Frazeysburg"],
    "Noble County": ["Caldwell", "Shawnee", "Sarahsville"],
    "Ottawa County": ["Port Clinton", "Oak Harbor", "Put-in-Bay"],
    "Paulding County": ["Paulding", "Oakwood", "Antwerp"],
    "Perry County": ["New Lexington", "Somerset", "Sherrodsville"],
    "Pickaway County": ["Circleville", "Ashville", "Logan Elm Village"],
    "Pike County": ["Waverly", "Piketon", "Oak Hill"],
    "Portage County": ["Ravenna", "Kent", "Brimfield"],
    "Preble County": ["Eaton", "Camden", "Lewisburg"],
    "Putnam County": ["Ottawa", "Leipsic", "Kalida"],
    "Richland County": ["Mansfield", "Ontario", "Shelby"],
    "Ross County": ["Chillicothe", "Frankfort", "Huntington"],
    "Sandusky County": ["Fremont", "Clyde", "Green Springs"],
    "Scioto County": ["Portsmouth", "Lucasville", "Wheelersburg"],
    "Seneca County": ["Tiffin", "Fostoria", "Attica"],
    "Shelby County": ["Sidney", "Anna", "Russia"],
    "Stark County": ["Canton", "Massillon", "North Canton"],
    "Summit County": ["Akron", "Cuyahoga Falls", "Stow", "Barberton"],
    "Trumbull County": ["Warren", "Niles", "Girard", "Howland"],
    "Tuscarawas County": ["New Philadelphia", "Dover", "Dennison"],
    "Union County": ["Marysville", "Plain City", "Unionville Center"],
    "Van Wert County": ["Van Wert", "Delphos", "Creston"],
    "Vinton County": ["McArthur", "Hamden", "Zaleski"],
    "Warren County": ["Lebanon", "Mason", "Springboro"],
    "Washington County": ["Marietta", "Belpre", "Macksburg"],
    "Wayne County": ["Wooster", "Rittman", "Creston"],
    "Williams County": ["Bryan", "Montpelier", "Edgerton"],
    "Wood County": ["Bowling Green", "Oregon", "Perrysburg"],
    "Wyandot County": ["Upper Sandusky", "Sycamore", "Wharton"]
}

ohio_cities = {
    "West Union": 2963,           # West Union, Adams County
    "Peebles": 1536,
    "Seaman": 627,
    "Lima": 34387,
    "Beaverdam": 370,
    "Delphos": 6878,
    "Ashland": 19270,
    "Loudonville": 2043,
    "Ontario": 6225,
    "Ashtabula": 18003,
    "Conneaut": 12131,
    "Geneva": 6366,
    "Jefferson": 3791,
    "Painesville": 17224,
    "Athens": 22698,
    "Coolville": 717,
    "Albany": 844,
    "Nelsonville": 5495,
    "Wapakoneta": 9681,
    "St. Marys": 8616,
    "Minster": 3884,
    "New Knoxville": 844,
    "St. Clairsville": 3894,
    "Martins Ferry": 5588,
    "Bridgeport": 2335,
    "Powhatan Point": 880,
    "Georgetown": 3819,
    "Mount Orab": 6166,
    "Aberdeen": 1298,
    "Hamilton": 62937,
    "Fairfield": 44447,
    "Middletown": 51478,
    "Trenton": 16607,
    "Oxford": 24541,
    "Monroe": 14354,
    "Carrollton": 3306,
    "Malvern": 2723,
    "Dellroy": 582,
    "Urbana": 11357,
    "West Liberty": 1806,
    "Mechanicsburg": 1650,
    "Springfield": 58082,
    "Enon": 2294,
    "South Charleston": 1928,
    "Batavia": 2606,
    "Amelia": 12388,
    "Milford": 14095,
    "Loveland": 13508,
    "Wilmington": 12416,
    "Blanchester": 4312,
    "Sabina": 2645,
    "Lisbon": 2057,
    "Salem": 12140,
    "East Liverpool": 9753,
    "Columbiana": 6368,
    "Coshocton": 11232,
    "Conesville": 319,
    "West Lafayette": 1120,
    "Bucyrus": 11507,
    "Galion": 10617,
    "Crestline": 5656,
    "Cleveland": 361607,
    "Parma": 78951,
    "Lakewood": 49913,
    "Euclid": 48212,
    "Cleveland Heights": 43908,
    "Strongsville": 45511,
    "Greenville": 13519,
    "Union City": 725,
    "Ansonia": 988,
    "Defiance": 16550,
    "Hicksville": 3021,
    "Sherwood": 585,
    "Delaware": 45158,
    "Powell": 13296,             # Powell, Delaware County
    "Olentangy": 1189,           # Olentangy is a township; included population estimate
    "Sunbury": 9729,
    "Sandusky": 24351,
    "Huron": 7227,
    "Vermilion": 10444,
    "Port Clinton": 6395,
    "Lancaster": 41422,
    "Pickerington": 23818,
    "Baltimore": 2968,
    "Berne": 150,
    "Washington Court House": 14370,
    "Junction City": 1612,
    "Jeffersonville": 1928,
    "Columbus": 907971,
    "Bexley": 13315,
    "Gahanna": 35159,
    "Upper Arlington": 35743,
    "Whitehall": 18926,
    "Westerville": 37958,
    "Dublin": 49892,
    "New Albany": 19695,
    "Wauseon": 7143,
    "Swanton": 3394,
    "Delta": 3866,
    "Gallipolis": 3954,
    "Bidwell": 588,
    "Vinton": 1270,
    "Chardon": 5556,
    "Middlefield": 5426,
    "Parkman": 1611,
    "Burton": 1648
}  
